#!/bin/sh

VENVDIR=$1
#VENVDIR=/media/bigdisk/ws_venv

python3 -m venv $VENVDIR
cd $VENVDIR
source ./bin/activate

mkdir -p git
cd git

#First time:
#git clone https://github.com/stts-se/wikispeech-server.git


cd wikispeech-server
git pull
mkdir -p wikispeech_server/tmp


pip3 install -r requirements.txt

#should now work (except lexicon and marytts servers may need to be configured and/or started):
python3 bin/wikispeech

#To quit venv:
#deactivate
