#!/bin/bash

CMD=`basename $0`

TIMEOUT=600
s1=$1
s2=$2
audio_url_prefix=$3

s1host=`echo $s1|cut -f1 -d:`
s1port=`echo $s1|cut -f2 -d:`

s2host=`echo $s2|cut -f1 -d:`
s2port=`echo $s2|cut -f2 -d:`

for i1 in `seq $TIMEOUT` ; do
    echo "[$CMD] Waiting for $s1 to start" 2>&1
    nc -z $s1host $s1port > /dev/null 2>&1
    curl $s1 > /dev/null 2>&1
    
    result=$?
    if [ $result -eq 0 ] ; then

	for i2 in `seq $TIMEOUT` ; do
	    echo "[$CMD] Waiting for $s2 to start" 2>&1
	    nc -z $s2host $s2port > /dev/null 2>&1
	    curl $s2 > /dev/null 2>&1
	    
	    result=$?
	    if [ $result -eq 0 ] ; then
		echo "[$CMD] All required servers up and running, starting wikispeech" 2>&1
		if cd /wikispeech_mockup ; then
		    mv docker/config/docker-compose.conf docker/config/docker-compose.conf.BAK
                    sed 's/<AUDIO_URL_PREFIX>/${audio_url_prefix}/' docker/config/docker-compose.conf.BAK > docker/config/docker-compose.conf
		    python3 bin/wikispeech docker/config/docker-compose.conf
		    exit $?
		else
		    exit 1
		fi
	    fi
	    sleep 5
	done

    fi
    sleep 5
done

echo "[$CMD] Reached timeout for service dependencies: $s1 && $s2" 2>&1
