#!/bin/bash

TIMEOUT=15
s1=$1
s2=$2

for i in `seq $TIMEOUT` ; do
    curl $s1 > /dev/null 2>&1
    
    result=$?
    if [ $result -eq 0 ] ; then

	for j in `seq $TIMEOUT` ; do
	    curl $s2 > /dev/null 2>&1
	    
	    result=$?
	    if [ $result -eq 0 ] ; then
	       python3 bin/wikispeech
		exit 0
	    fi
	    sleep 1
	done

    fi
    sleep 1
done

echo "Reached timeout for service dependencies: $s1 && $s2" 2>&1
