#!/bin/bash

TIMEOUT=15
s1=$1
s2=$2

s1host=`echo $s1|cut -f1 -d:`
s1port=`echo $s1|cut -f2 -d:`

s2host=`echo $s2|cut -f1 -d:`
s2port=`echo $s2|cut -f2 -d:`

#set -e

for i in `seq $TIMEOUT` ; do
    nc -z $s1host $s1port #> /dev/null 2>&1
    #curl $s1
    
    result=$?
    if [ $result -eq 0 ] ; then

	for j in `seq $TIMEOUT` ; do
	    nc -z $s2host $s2port # > /dev/null 2>&1
	    #curl $s2
	    
	    result=$?
	    if [ $result -eq 0 ] ; then
		python3 wikispeech_mockup/bin/wikispeech
		exit 0
	    fi
	    sleep 1
	done

    fi
    sleep 1
done

echo "Reached timeout for service dependencies: $s1 && $s2" 2>&1
