#!/bin/bash

TIMEOUT=15
s1=$1
s2=$2
s1host=`echo $s1 | cut -f1 -d:`
s1port=`echo $s1 | cut -f2 -d:`

for i in `seq $TIMEOUT` ; do
    nc -z $s2host $s1port > /dev/null 2>&1
    
    result=$?
    if [ $result -eq 0 ] ; then

	for j in `seq $TIMEOUT` ; do
	    nc -z $s2host $s2port > /dev/null 2>&1
	    
	    result=$?
	    if [ $result -eq 0 ] ; then
	       `python3 bin/wikispeech`
		exit 0
	    fi
	    sleep 1
	done

    fi
    sleep 1
done

echo "Reached timeout for service dependencies: $s1 && $s2" 2>&1
