# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Status Minimal

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Set up env
      run: |
       echo "LEXDATA_RELEASE=master" >> $GITHUB_ENV

    - name: Install dependencies for wikispeech-server
      run: |
       curl -LsSf https://astral.sh/uv/install.sh | sh
       sudo apt install opus-tools
       uv venv
       source .venv/bin/activate
       uv pip install flake8 pytest
       uv pip install -r requirements.txt
       mkdir -p wikispeech_server/tmp

    - name: Lint with flake8
      run: |
       source .venv/bin/activate
       # stop the build if there are Python syntax errors or undefined names
       flake8 . --bug-report --count --select=E9,F63,F7,F82 --show-source --statistics
       # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
       flake8 . --bug-report --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --extend-ignore=E501,E266

    #- name: Test with pytest
    #  run: |
    #   pytest
    
    - name: Set up symbolset/mapper + pronlex/lexserver
      run: |
       git clone https://github.com/stts-se/symbolset
       git clone https://github.com/stts-se/pronlex
       git clone https://github.com/stts-se/wikispeech-lexdata
       
       cd symbolset/server
       bash setup.sh ../../wikispeech-lexdata ss_files

       cd ../../pronlex
       APPDIR=/tmp/appdir/sqlite
       LOC=/tmp/appdir/sqlite
       ENGINE=sqlite
       PORT=8780
       bash scripts/setup.sh -a $APPDIR -e $ENGINE -l $LOC
       bash scripts/import.sh -e $ENGINE -f ../wikispeech-lexdata -a $APPDIR -r $LEXDATA_RELEASE -l $LOC

    - name: Start symbolset/mapper server
      run: |
       # Start symbolset/mapper server
       cd symbolset/server
       go run *.go -ss_files ss_files &> ../../mapper.log &
       
    - name: Start pronlex/lexserver server
      run: |
       # Start pronlex/lexserver
       cd pronlex
       APPDIR=/tmp/appdir/sqlite
       LOC=/tmp/appdir/sqlite
       ENGINE=sqlite
       PORT=8780
       bash scripts/start_server.sh -a $APPDIR -e $ENGINE -l $LOC -p $PORT &> ../pronlex.log &

    - name: Set up wikispeech-tts-wrappers
      run: |
       git clone https://github.com/stts-se/wikispeech-tts-wrappers
       cd wikispeech-tts-wrappers
       sudo apt install espeak-ng
       uv venv
       source .venv/bin/activate
       
       # fix for circular dependency error with torch versions
       uv pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu
       uv pip install torchvision==0.17.2
       
       uv pip install -r textproc/requirements.txt
       uv pip install -r piper_server/requirements.txt
       uv pip install -r matcha_server/requirements.txt
       # workaround for pytorch
       sed -i 's/checkpoint = torch.load(checkpoint_path, map_location=device)/checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)/' .venv/lib/python3.*/site-packages/dp/model/model.py
       # workarounds for matcha
       sed -i 's/MatchaTTS.load_from_checkpoint(checkpoint_path, map_location=device)/MatchaTTS.load_from_checkpoint(checkpoint_path, map_location=device, weights_only=False)/' .venv/lib/python3.*/site-packages/matcha/cli.py
       sed -i 's|\(plot_spectrogram_to_numpy.*\) f"{filename}.png")|\1 folder / f"{filename}.png")|' .venv/lib/python3.*/site-packages/matcha/cli.py
      
    - name: Fetch models
      run: |
       # Fetch models
       mkdir -p $HOME/.local/share/piper_tts
       cd $HOME/.local/share/piper_tts
       curl -f -L https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/medium/ar_JO-kareem-medium.onnx -o ar_JO-kareem-medium.onnx
       curl -f -L https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/medium/ar_JO-kareem-medium.onnx.json -o ar_JO-kareem-medium.onnx.json
       curl -f -L https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/bryce/medium/en_US-bryce-medium.onnx -o en_US-bryce-medium.onnx
       curl -f -L https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/bryce/medium/en_US-bryce-medium.onnx.json -o en_US-bryce-medium.onnx.json

       mkdir -p $HOME/.local/share/matcha_tts
       cd $HOME/.local/share/matcha_tts
       curl -f -L https://github.com/shivammehta25/Matcha-TTS-checkpoints/releases/download/v1.0/generator_v1 -o hifigan_T2_v1
       curl -f -L https://github.com/shivammehta25/Matcha-TTS-checkpoints/releases/download/v1.0/g_02500000 -o hifigan_univ_v1
       curl -f -L https://github.com/shivammehta25/Matcha-TTS-checkpoints/releases/download/v1.0/matcha_ljspeech.ckpt -o matcha_ljspeech.ckpt
       curl -f -L https://github.com/shivammehta25/Matcha-TTS-checkpoints/releases/download/v1.0/matcha_vctk.ckpt -o matcha_vctk.ckpt

    - name: Start textproc server
      run: |
       # Start textproc
       cd wikispeech-tts-wrappers
       source .venv/bin/activate
       cd textproc
       uvicorn textproc_server:app --env-file config_sample.env --port 8011 &> ../../textproc.log &
       sleep 2

    - name: Start piper server
      run: |
       # Start piper
       cd wikispeech-tts-wrappers
       source .venv/bin/activate
       cd piper_server
       uvicorn piper_server:app --env-file config_minimal.env --port 8010 &> ../../piper.log & 
       sleep 2

    - name: Start matcha server
      run: |
       # Start matcha
       cd wikispeech-tts-wrappers
       source .venv/bin/activate
       cd matcha_server
       uvicorn matcha_server:app --env-file config_minimal.env --port 8009 &> ../../matcha.log &
       sleep 20

    - name: Start wikispeech-server
      run: |
       # Start wikispeech-server
       source .venv/bin/activate
       python3 bin/wikispeech .github/workflows/ws-config-minimal.conf &> wikispeech.log &
       sleep 2

   - name: Log files
      run: |
       # Log files
       cat mapper.log
       cat pronlex.log
       cat textproc.log
       cat piper.log
       cat matcha.log
       cat wikispeech.log       

   - name: Ping servers
      run: |
       # Ping servers

       curl -f http://localhost:8771/ping  # symbolset/mapper
       echo ""
       
       curl -f http://localhost:8780/ping  # pronlex/lexserver
       echo ""
       
       curl -f http://localhost:8011/ping  # textproc
       echo ""

       curl -f http://localhost:8010/ping  # piper
       echo ""
       
       curl -f http://localhost:8009/ping  # matcha
       echo ""
       
       curl -f http://localhost:10000/ping # wikispeech-server
       echo ""
 
