# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Status

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Set up env
      run: |
       echo "RELEASE=master" >> $GITHUB_ENV

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #     mkdir wikispeech_server/tmp

    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --bug-report --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --bug-report --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --extend-ignore=E501,E266

    #- name: Test with pytest
    #  run: |
    #    pytest
    
    - name: Set up symbolset/mapper
      run: |
       git clone https://github.com/stts-se/symbolset
       cd symbolset
       go build -v ./...
       go test -v ./...
       cd server
       git clone https://github.com/stts-se/wikispeech-lexdata.git
       cd wikispeech-lexdata
       git checkout $RELEASE || echo "No such release for lexdata. Using master."
       cd ..
       bash setup.sh wikispeech-lexdata ss_files
       
       go run *.go -ss_files ss_files &
       
    - name: Set up pronlex/lexserver
      run: |
       git clone https://github.com/stts-se/pronlex
       cd pronlex
       APPDIR=/tmp/appdir/sqlite
       LOC=/tmp/appdir/sqlite
       ENGINE=sqlite
       PORT=8780
       bash scripts/setup.sh -a $APPDIR -e $ENGINE -l $LOC
       bash scripts/import.sh -e $ENGINE -f wikispeech-lexdata -a $APPDIR -r $RELEASE -l $LOC
       
       bash scripts/start_server.sh -a $APPDIR -e $ENGINE -l $LOC -p $PORT &

    - name: Set up textproc
      run: |
       git clone https://github.com/stts-se/wikispeech-tts-wrappers
       cd wikispeech-tts-wrappers/textproc
       python -m pip install --upgrade pip
       pip install flake8 pytest
       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
       
       uvicorn textproc_server:app --env-file config_sample.env --port 8011 &


    - name: Ping servers
      run: |
       curl -f http://localhost:8771/ping  # symbolset/mapper
       curl -f http://localhost:8780/ping  # pronlex/lexserver
       curl -f http://localhost:8011/ping  # textproc
       # curl -f http://localhost:8009/ping  # matcha
       # curl -f http://localhost:8010/ping  # piper
       # curl -f http://localhost:10000/ping # wikispeech-server
 

